name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to report a bug!**
  
  - type: input
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Add links to screenshots or upload them directly
    validations:
      required: false

  - type: input
    id: desktop_info
    attributes:
      label: Desktop (please complete the following information)
      description: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
      placeholder: |
        - OS: 
        - Browser: 
        - Version: 
    validations:
      required: false

  - type: input
    id: smartphone_info
    attributes:
      label: Smartphone (please complete the following information)
      description: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
      placeholder: |
        - Device: 
        - OS: 
        - Browser: 
        - Version: 
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Provide additional context
    validations:
      required: false
